name: Pull image

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    name: Build latest
    runs-on: ubuntu-20.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - run: docker pull ghcr.io/micro-fan/prometheus-http-discovery:latest || true
    - run: TAG_NAME=latest make push_ghcr_image
